export const trigram_info = [
  {
    trigram_name: "乾",
    pre_num: 1,
    zh_name: "天",
    wuxing: "金",
    gan: "庚",
    zhi: "戌亥",
    yy: 1,
    after_num: 6,
    yao_yy: "111",
    yao_yang_num: 3,
    yao_yin_num: 0,
  },
  {
    trigram_name: "兑",
    pre_num: 2,
    zh_name: "泽",
    wuxing: "金",
    gan: "辛",
    zhi: "酉",
    yy: 0,
    after_num: 7,
    yao_yy: "011",
    yao_yang_num: 2,
    yao_yin_num: 1,
  },
  {
    trigram_name: "离",
    pre_num: 3,
    zh_name: "火",
    wuxing: "火",
    gan: "丙丁",
    zhi: "午",
    yy: 0,
    after_num: 9,
    yao_yy: "101",
    yao_yang_num: 2,
    yao_yin_num: 1,
  },
  {
    trigram_name: "震",
    pre_num: 4,
    zh_name: "雷",
    wuxing: "木",
    gan: "甲",
    zhi: "卯",
    yy: 1,
    after_num: 3,
    yao_yy: "001",
    yao_yang_num: 1,
    yao_yin_num: 2,
  },
  {
    trigram_name: "巽",
    pre_num: 5,
    zh_name: "风",
    wuxing: "木",
    gan: "乙",
    zhi: "辰巳",
    yy: 0,
    after_num: 4,
    yao_yy: "110",
    yao_yang_num: 2,
    yao_yin_num: 1,
  },
  {
    trigram_name: "坎",
    pre_num: 6,
    zh_name: "水",
    wuxing: "水",
    gan: "壬癸",
    zhi: "子",
    yy: 1,
    after_num: 1,
    yao_yy: "010",
    yao_yang_num: 1,
    yao_yin_num: 2,
  },
  {
    trigram_name: "艮",
    pre_num: 7,
    zh_name: "山",
    wuxing: "土",
    gan: "戊",
    zhi: "寅丑",
    yy: 1,
    after_num: 8,
    yao_yy: "100",
    yao_yang_num: 1,
    yao_yin_num: 2,
  },
  {
    trigram_name: "坤",
    pre_num: 8,
    zh_name: "地",
    wuxing: "土",
    gan: "己",
    zhi: "未申",
    yy: 0,
    after_num: 2,
    yao_yy: "000",
    yao_yang_num: 0,
    yao_yin_num: 3,
  },
];
